### ISSUE TITLE
We must have an app event to listen result of auto login

### ISSUE THREAD

**Issue by CharlesGrimont** [convertigo/convertigo#162]
In somes cases, we need to get result of a login, if the sdk perform an autologin, we must be able to handle autologin event and get response.

api:
c8o.handleAutoLoginResponse().subscribe((res)=>{
// res : {status:true, response: response, error: null}
})

status is true if we logged in successfully

Feature available in sdk 3.0.1-beta1

**Comment by nathalie-lammelin** [comment]
Need a new _tpl

**Comment by nathalie-lammelin** [comment]
Sample project (which need a **mobilebuilder_tpl_7_7_0** with version **7.7.0.1** min) : 
[issue162.zip](https://github.com/convertigo/convertigo/files/3406654/issue162.zip)

**Comment by gregory-vorbe** [comment]
In **Convertigo EMS Studio 7.7.0_beta (build 06399-develop-7.7.0-beta)**

I tested with issue162 project.
I guess I have to click the LOGIN button, then the LOGOUT one.
Is it the expected behaviour with this sample project that the application is looping on displaying the "Logged in OK" toast ?
![issue_01_AutoLogin](https://user-images.githubusercontent.com/1685373/71970781-a1457680-3209-11ea-9ab4-d7bc581ba5f9.gif)

**Comment by nathalie-lammelin** [comment]
@gregory-vorbe 
I do not think so. It seems to me that we used to receive the event for the autologin only once ...

**Comment by gregory-vorbe** [comment]
I still have the loop issue (https://github.com/convertigo/convertigo/issues/162#issuecomment-571986606) in **Convertigo EMS Studio 7.9.0_beta (build 10051-develop-7.9.0-beta)**
Steps: Click LOGIN button, then LOGOUT button, it should automatically execute Login sequence, but it executes Logout sequence too and so on.
It loops on Sequences **Logout** -> **Login** -> **Logout** -> **Login**...
I tried to change **Disable auto login** property false/true on Login/Logout sequences but didn't get expected behaviour.

**Comment by CharlesGrimont** [comment]
In SDK angular with auto login enabled,  

when we have an authenticated user,  

then we ensure that any request executed will we done with an authenticated context, and if not, we will perform auto login and then re-execute request. 

Since sequence logout execute a step `remove authenticated user`,  

It will be executed and will return a non-authenticated header to the SDK. 

The latter will perform auto login and then re execute the request logout. 

  

It results of an infinite loop with Sequences that calls a step `remove authenticated user`  

  

The solution is to set property `Disable auto login to true` when calling this kind of sequences to prevent from these kind of behavior

**Comment by gregory-vorbe** [comment]
Ok, this is quite clear now and explain ther behaviour in the project. Finally, it still proves the auto login feature and the event are working.
