### ISSUE TITLE
Add support for variabilizing SharedComponent

### ISSUE THREAD

**Issue by CharlesGrimont** [convertigo/convertigo#191]
When we use a shared component, we want to be able to give him entry variables.

**Comment by nathalie-lammelin** [comment]
@CharlesGrimont : should be ok since last commit (no more duplicates, customAction regression fixed)

**Comment by nathalie-lammelin** [comment]
Since last commit, for each page using shared components you should see in page.html : 
- an `ng-template` for each `SharedComponent` used
- an `ng-container` for each `UseSharedComponent` 
  the targeted shared component `ng-template` is referenced through the `*ngTemplateOutlet` directive, passing also  a `context` with needed parameters/variables

Using `ng-template` makes `SharedComponent` really reusable.
You can also have recursive `SharedComponent` :)

**Comment by nathalie-lammelin** [comment]
Close: reopen if needed

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.7.0_beta (build 06351-develop-7.7.0-beta)**

- The **params\<priority>.\<variable-name>** reference is not an easy part, A picker would be welcomed.
