### ISSUE TITLE
Property of bean "CallSequence" is wrong

### ISSUE THREAD

**Issue by CharlesGrimont** [convertigo/convertigo#203]
When we let property "Disable loading controller" to notset its disable loading controller 

it should let it enabled

Bug seen in 7.6.4

**Comment by nathalie-lammelin** [comment]
> When we let property "Disable loading controller" to notset its disable loading controller
> 
> it should let it enabled
> 
> Bug seen in 7.6.4

Same thing for all actions having the `noLoading` property : 
`CallSequence,CallFullSync,FullSyncGet,FullSyncPost,FullSyncDelete,FullSyncPutAttachment,FullSyncDeleteAttachment,FullSyncView`
This is due to missing default value for **boolean** property in ion_objects.json file (sdk does not handle the` not set` 'null' value for boolean).

=> Others boolean properties must be reviewed in file.

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.6.5_beta (build 05275-hotfix-7.6.5-7.6.5-beta)**
