### ISSUE TITLE
Modify CustomAction default debug trace

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#262]
`page.c8o.log.debug(event ? event.toString():'no event');` is not suitable.

**Comment by nathalie-lammelin** [comment]
Modified for `page.c8o.log.debug('[MB] '+ props.actionFunction +': '+ props.actionName);`
which generate at runtime : `(72.652) [debug] [MB] CTS1574348859733: InitUserArray`

**Comment by opicciotto** [comment]
Top : )



A+

OPIC







*De :* Nathalie LAMMELIN <notifications@github.com>
*Envoyé :* jeudi 21 novembre 2019 16:55
*À :* convertigo/convertigo <convertigo@noreply.github.com>
*Cc :* Subscribed <subscribed@noreply.github.com>
*Objet :* Re: [convertigo/convertigo] Modify CustomAction default debug
trace (#262)



Modified for page.c8o.log.debug('[MB] '+ props.actionFunction +': '+
props.actionName);
which generate at runtime : (72.652) [debug] [MB] CTS1574348859733:
InitUserArray

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/convertigo/convertigo/issues/262?email_source=notifications&email_token=AAH64FCAHIPNNFTRA7LQQHDQU2VOBA5CNFSM4JQDBO6KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEE2WQMY#issuecomment-557148211>,
or unsubscribe

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.7.0_beta (build 05968-develop-7.7.0-beta)**
