### ISSUE TITLE
Connection string of a SQL connector does not override user/pwd properties

### ISSUE THREAD

**Issue by gregory-vorbe** [convertigo/convertigo#369]
You can override the **Database URL** property of a **SQL connector** by using a **connection string** in the call transaction Step.
For example: `jdbc:mariadb://localhost:3306/DB?user=root&password=myPassword`
But properties **User name** and **User password** are not overriden and are mandatory to establish connection.
If these properties are left empty the connection to the database should use the Database URL.

**Comment by nathalie-lammelin** [comment]
Done.
**Note**: empty value are accepted for user & password. Do not pass user and/or password to use connector's default values.

**! Need non regression tests to be done on various databases !**
Since [convertigo-08890-hotfix-7.8.1-7.8.1-beta](https://convertigo-ci.s3-eu-west-3.amazonaws.com/index.html?prefix=convertigo-08890-hotfix-7.8.1-7.8.1-beta/)

**Comment by nathalie-lammelin** [comment]
Fixed.
Since [convertigo-08938-hotfix-7.8.1-7.8.1-beta](https://convertigo-ci.s3-eu-west-3.amazonaws.com/index.html?prefix=convertigo-08938-hotfix-7.8.1-7.8.1-beta/)

**Comment by nathalie-lammelin** [comment]
Reopen. Some Studio tests with Oracle pools fail.

**Comment by nathalie-lammelin** [comment]
Wrong tests. Close issue. Works well.

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.8.1_beta (build 08938-hotfix-7.8.1-7.8.1-beta)**

- Tested with Oracle driver and MariaDB driver
