### ISSUE TITLE
We cant' source on step ReadCSV if property "Title line" is set to true

### ISSUE THREAD

**Issue by CharlesGrimont** [convertigo/convertigo#683]
We cant' source on step ReadCSV if property "Title line" is set to true.

see gif below:
![bugSTEPCSV](https://user-images.githubusercontent.com/11558728/203937816-6cf5171f-090f-45f7-be64-8bb2fa661bd8.gif)

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.1.1_beta (build 14744-hotfix-8.1.1-8.1.1-beta)**

- This is not only due to the property Title line true, it is also due to the property Source bound to a sequence variable. If you hardcode the name of the CSV file it works in previous version. Now, it will work but the schema will be always the same (document->line->col).
