### ISSUE TITLE
Map all Mobile palette documentation links to ionc3 docs

### ISSUE THREAD

**Issue by opicciotto** [convertigo/convertigo#69]
Links from the mobile palette docs are now ending on the Ionic V4 doc we have to change them to the Ionic 3.

**Comment by gregory-vorbe** [comment]
- **Check Install** component has **File Opener** link name and href.

**Comment by gregory-vorbe** [comment]
**Uninstaller** component has **File Opener** link name and href.

**Comment by gregory-vorbe** [comment]
Blank page for **Treeview** componnent doc link.

**Comment by nathalie-lammelin** [comment]
should we close ?

**Comment by nicolas-albert** [comment]
Not good for some components (components in JAVA) that point to `ionObject.json` instead of the `.properties`.

Like :
https://www.convertigo.com/documentation/develop/reference-manual/convertigo-objects/mobile-application/components/control-components/appevent/
https://www.convertigo.com/documentation/develop/reference-manual/convertigo-objects/mobile-application/components/action-components/variable/

**Comment by nicolas-albert** [comment]
Wrong comment!

**Comment by nathalie-lammelin** [comment]
Ok with convertigo-03862-release-7.6.0-7.6.0.
