### ISSUE TITLE
A textInput should NEVER have a property [ngModel]="''" generated when it's property binding is set no not set

### ISSUE THREAD

**Issue by CharlesGrimont** [convertigo/convertigo#707]
A textInput should **NEVER** have a property [ngModel]="''" generated when it's property binding is set no not set

It must not be generated At all

it prevents from using formGroups and validators

**Comment by opicciotto** [comment]
When the binding is set to 'not set' the ngModel is not generated. The problem comes when the user sets a binding in TS mode. and wants to clear it. in this case he cannot set it to empty and the ngModel is still generated. The only way to no generate it is to set the binding in TX mode and select not set.

**Comment by nicolas-albert** [comment]
**Ok for convertigo-studio-8.2.0-beta-win64**
