### ISSUE TITLE
Visual App Viewer not completing install or downloading dependencies

### ISSUE THREAD

**Issue by JetDev162** [convertigo/convertigo#756]
I have just instaled the new release of Convertigo Studio Version 8.2.1
My System
OS: Windows 10, v.10.0, x86_64 / win32
Java vendor: Eclipse Adoptium
Java runtime version: 17.0.6+10
Java version: 17.0.6

The App Viewer wont finnish installing or downloading the dependancies and gets stuck on
Thread:ConvertigoExecuter-163
getLocalNodeDir C:\Users\TKS\Convertigo\Studio 8.2.0\workspace\.metadata\.plugins\com.twinsoft.convertigo.studio\nodes\node-v16.18.0-win-x64 exists
I have also noticed that the Ngx Palette is not the same as the Convertigo Studio 8.1.0

Screen Shot
![Convertigo Screen shot](https://github.com/convertigo/convertigo/assets/76776368/58238e5a-5154-4727-aa29-a764b34fddae)

**Comment by nicolas-albert** [comment]
Hi,
Do you confirm this is an update from the 8.2.0 release? (software update menu)
This project was already built and running from the 8.2.0?

Normally it should work like before.

You can try on the `NgxApp` object to launch the `Re-install packages and Execute` from its contextual menu.

OR

Turn off the studio and remove (or rename) those folders:
- `C:\Users\TKS\Convertigo\Studio 8.2.0\workspace\.metadata\.plugins\com.twinsoft.convertigo.studio\nodes`
- `C:\Users\TKS\Convertigo\Studio 8.2.0\workspace\JetPOS\_private`

Then start the Studio and retry to build the project.

Tell us if it is enough.

PS: Since 8.2.0, the NGX Palette have been replaced by a more generic Palette for all Convertigo Objects (also for backend).
